[project]
name = "dinkisstyle-bora-ubuntu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "evdev>=1.9.2",
    "keyboard>=0.13.5",
    "pyinstaller>=6.17.0",
]
